version: '2'
services:
   awecms:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - ./:/var/www/html
      links:
        - database:database
      ports:
        - 80:80
   database:
      image: couchdb
