version: '2'
services:
   awecms:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - ./:/var/www/html
      ports:
        - 8110:80
      links:
        - mysql:mysql
   mysql:
      image: mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: awecms
